name: Lint
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba env update -n test -f environment.yml
      - name: Run codespell
        shell: bash -l {0}
        run: codespell forsake test
      - name: Run pycodestyle
        shell: bash -l {0}
        run: pycodestyle forsake test
      - name: Run black
        shell: bash -l {0}
        run: |
          black --check --diff forsake test
