name: Test
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.on }}
    strategy:
      matrix:
        on:
          - ubuntu-22.04
          - macos-latest
        python:
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest", python-version: "${{ matrix.python }}" }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba env update -n test --quiet -f environment.yml
          conda list
      - name: Install forsake
        shell: bash -l {0}
        run: |
          pip install --verbose --no-index .
      - name: Run pytest
        shell: bash -l {0}
        run: pytest
